FROM node:14-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

COPY ./packages/sfy-next-start/public ./public
COPY ./packages/sfy-next-start/.next ./.next
COPY ./packages/sfy-next-start/package.json ./package.json
COPY ./node_modules ./node_modules

EXPOSE 3000

ENV PORT 3000

CMD ["node_modules/.bin/next", "start"]